### ISSUE TITLE
guides to bright

### ISSUE THREAD

**Issue by palango** [javaguirre/atom-jellybeans#2]
I really like the theme, but the guides for indention are to bright in my eyes. They should be more subtle. See screenshot.

![screen shot 2015-07-29 at 15 58 40](https://cloud.githubusercontent.com/assets/90851/8959412/fea1662c-360a-11e5-91c0-8b26c2e20ee7.png)

**Comment by javaguirre** [comment]
You are right, would you like to check which color could fit best so we can change it?

**Comment by javaguirre** [comment]
Much better now, I'm gonna submit an update.

<img width="494" alt="screen shot 2015-11-03 at 10 43 08" src="https://cloud.githubusercontent.com/assets/488556/10905028/bb856d44-8217-11e5-98bb-ea49ad957420.png">
